# Generated by Django 3.2.15 on 2022-08-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comnents',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
