# Generated by Django 3.2.15 on 2022-08-21 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 8, 21, 3, 1, 18, 862708, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
